# Generated by Django 3.0.8 on 2021-10-20 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=8)),
                ('pais', models.IntegerField(choices=[('0', 'GUATEMALA')])),
                ('region', models.IntegerField(choices=[('0', 'Alta Verapaz'), ('1', 'Baja Verapaz'), ('2', 'Chimaltenago'), ('3', 'Chiquimula'), ('4', 'Guatemala'), ('5', 'El Progreso'), ('6', 'Escuintla'), ('7', 'Huehuetenango'), ('8', 'Izabal'), ('9', 'Jalapa'), ('10', 'Jutiapa'), ('11', 'Petén'), ('12', 'Quetzaltenango'), ('13', 'Quiché'), ('14', 'Retalhuleu'), ('15', 'Sacatepequez'), ('16', 'San Marcos'), ('17', 'Santa Rosa'), ('18', 'Sololá'), ('19', 'Suchitepequez'), ('20', 'Totonicapán'), ('21', 'Zacapa')])),
                ('direccion', models.CharField(max_length=150)),
                ('referencia', models.CharField(max_length=150)),
                ('zipcode', models.CharField(max_length=6)),
                ('default', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Direccion',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_orden', models.DateTimeField(auto_now_add=True)),
                ('fecha_orden', models.DateTimeField(blank=True, null=True)),
                ('ordenada', models.BooleanField(default=False)),
                ('direccion_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='carrito.Direccion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orden_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('imagen', models.ImageField(upload_to='producto_imagen')),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='carrito.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carrito.Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.Producto')),
            ],
        ),
    ]
