# Generated by Django 3.0.8 on 2021-10-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.IntegerField(choices=[('0', ''), ('1', 'GUATEMALA')]),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='region',
            field=models.IntegerField(choices=[('0', ''), ('1', 'Alta Verapaz'), ('2', 'Baja Verapaz'), ('3', 'Chimaltenago'), ('4', 'Chiquimula'), ('5', 'Guatemala'), ('6', 'El Progreso'), ('7', 'Escuintla'), ('8', 'Huehuetenango'), ('9', 'Izabal'), ('10', 'Jalapa'), ('11', 'Jutiapa'), ('12', 'Petén'), ('13', 'Quetzaltenango'), ('14', 'Quiché'), ('15', 'Retalhuleu'), ('16', 'Sacatepequez'), ('17', 'San Marcos'), ('18', 'Santa Rosa'), ('19', 'Sololá'), ('20', 'Suchitepequez'), ('21', 'Totonicapán'), ('22', 'Zacapa')]),
        ),
    ]
