# Generated by Django 3.0.8 on 2021-10-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_auto_20211022_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.CharField(choices=[(1, 'Efectivo'), (2, 'Trasferencia')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='orden',
            name='direccion_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_entrega', to='carrito.Direccion'),
        ),
    ]
