# Generated by Django 3.0.8 on 2021-10-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_auto_20211025_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetodoDePago',
        ),
        migrations.AddField(
            model_name='orden',
            name='estado_pago',
            field=models.BooleanField(default=False),
        ),
    ]
